#!/usr/bin/env bash

PICTURES="$HOME/Pictures"
if command -v xdg-user-dir &>/dev/null; then
    PICTURES=$(xdg-user-dir PICTURES)
fi

# The path to use for wallpapers in light mode
if [ -z "$WALLPAPER_PATH" ]; then
    WALLPAPER_PATH=$PICTURES/Wallpapers/Shuffle
fi

# The path to use for wallpapers in dark mode
if [ -z "$WALLPAPER_PATH_DARK" ]; then
    WALLPAPER_PATH_DARK=$PICTURES/Wallpapers/Shuffle
fi

WALLPAPER=$(find "$WALLPAPER_PATH" -type f -name "*.jpg" -o -name "*.png" | shuf -n 1)
WALLPAPER_DARK=$(find "$WALLPAPER_PATH_DARK" -type f -name "*.jpg" -o -name "*.png" | shuf -n 1)

if command -v gsettings &>/dev/null; then
    gsettings set org.gnome.desktop.background picture-uri "file://$WALLPAPER"
    gsettings set org.gnome.desktop.background picture-uri-dark "file://$WALLPAPER_DARK"
fi

if command -v plasma-apply-wallpaperimage &>/dev/null; then
    # is there a way to do dark mode wallpapers in kde
    plasma-apply-wallpaperimage "$WALLPAPER"
fi
